WebMandaEmail/Models/ErrorViewModel.cs
using System;

namespace WebMandaEmail.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebMandaEmail/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebMandaEmail.Models;

namespace WebMandaEmail.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebMandaEmail/Controllers/SolicitacaoEmailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Infra;
using Infra.Entidade;

namespace WebMandaEmail.Controllers
{
    public class SolicitacaoEmailsController : Controller
    {
        private readonly ContextoBase _context;

        public SolicitacaoEmailsController(ContextoBase context)
        {
            _context = context;
        }

        // GET: SolicitacaoEmails
        public async Task<IActionResult> Index()
        {
            return View(await _context.SolicitacaoEmail.ToListAsync());
        }

        // GET: SolicitacaoEmails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitacaoEmail = await _context.SolicitacaoEmail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (solicitacaoEmail == null)
            {
                return NotFound();
            }

            return View(solicitacaoEmail);
        }

        // GET: SolicitacaoEmails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SolicitacaoEmails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Mensagem,Destinatarios,Enviado")] SolicitacaoEmail solicitacaoEmail)
        {
            if (ModelState.IsValid)
            {
                solicitacaoEmail.Enviado = false;
                _context.Add(solicitacaoEmail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(solicitacaoEmail);
        }

        // GET: SolicitacaoEmails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitacaoEmail = await _context.SolicitacaoEmail.FindAsync(id);
            if (solicitacaoEmail == null)
            {
                return NotFound();
            }
            return View(solicitacaoEmail);
        }

        // POST: SolicitacaoEmails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Mensagem,Destinatarios,Enviado")] SolicitacaoEmail solicitacaoEmail)
        {
            if (id != solicitacaoEmail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(solicitacaoEmail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SolicitacaoEmailExists(solicitacaoEmail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(solicitacaoEmail);
        }

        // GET: SolicitacaoEmails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitacaoEmail = await _context.SolicitacaoEmail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (solicitacaoEmail == null)
            {
                return NotFound();
            }

            return View(solicitacaoEmail);
        }

        // POST: SolicitacaoEmails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var solicitacaoEmail = await _context.SolicitacaoEmail.FindAsync(id);
            _context.SolicitacaoEmail.Remove(solicitacaoEmail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SolicitacaoEmailExists(int id)
        {
            return _context.SolicitacaoEmail.Any(e => e.Id == id);
        }
    }
}

WebMandaEmail/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebMandaEmail/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMandaEmail</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMandaEmail</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SolicitacaoEmails" asp-action="Index">Solicitações de email</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebMandaEmail - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebMandaEmail/Views/SolicitacaoEmails/Create.cshtml
@model Infra.Entidade.SolicitacaoEmail

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SolicitacaoEmail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mensagem" class="control-label"></label>
                <input asp-for="Mensagem" class="form-control" />
                <span asp-validation-for="Mensagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destinatarios" class="control-label"></label>
                <input asp-for="Destinatarios" class="form-control" />
                <span asp-validation-for="Destinatarios" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Enviado" /> @Html.DisplayNameFor(model => model.Enviado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMandaEmail/Views/SolicitacaoEmails/Delete.cshtml
@model Infra.Entidade.SolicitacaoEmail

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SolicitacaoEmail</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mensagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mensagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destinatarios)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destinatarios)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Enviado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Enviado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebMandaEmail/Views/SolicitacaoEmails/Details.cshtml
@model Infra.Entidade.SolicitacaoEmail

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SolicitacaoEmail</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mensagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mensagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destinatarios)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destinatarios)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Enviado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Enviado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebMandaEmail/Views/SolicitacaoEmails/Edit.cshtml
@model Infra.Entidade.SolicitacaoEmail

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SolicitacaoEmail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mensagem" class="control-label"></label>
                <input asp-for="Mensagem" class="form-control" />
                <span asp-validation-for="Mensagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destinatarios" class="control-label"></label>
                <input asp-for="Destinatarios" class="form-control" />
                <span asp-validation-for="Destinatarios" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Enviado" /> @Html.DisplayNameFor(model => model.Enviado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebMandaEmail/Views/SolicitacaoEmails/Index.cshtml
@model IEnumerable<Infra.Entidade.SolicitacaoEmail>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mensagem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destinatarios)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enviado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mensagem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destinatarios)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Enviado)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>